/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hospital_management_system;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class AppoitnmetnsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AppoitnmetnsPanel
     */
    public AppoitnmetnsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSAVE = new javax.swing.JButton();
        btnCLEAR = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnSEARCH = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        txtPID = new javax.swing.JTextField();
        txtDID = new javax.swing.JTextField();
        comboSTATUS = new javax.swing.JComboBox<>();
        spinnerTIME = new javax.swing.JSpinner();
        spinnerDATE = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setText("Patient Id");

        jLabel3.setText("Doctor Id");

        jLabel4.setText("Appointment Date");

        jLabel5.setText("Appointment Time");

        jLabel6.setText("Status");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Appointment Id", "Patient Id", "Doctor Id", "Appointment Date", "Appointment Time", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnSAVE.setText("SAVE");
        btnSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAVEActionPerformed(evt);
            }
        });

        btnCLEAR.setText("CLEAR");
        btnCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLEARActionPerformed(evt);
            }
        });

        btnUPDATE.setText("UPDATE");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnSEARCH.setText("SEARCH");
        btnSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEARCHActionPerformed(evt);
            }
        });

        btnDELETE.setText("DELETE");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        comboSTATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Ongoing", "Complete" }));

        spinnerTIME.setModel(new javax.swing.SpinnerDateModel());
        spinnerTIME.setEditor(new javax.swing.JSpinner.DateEditor(spinnerTIME, "HH:mm"));

        spinnerDATE.setModel(new javax.swing.SpinnerDateModel());
        spinnerDATE.setEditor(new javax.swing.JSpinner.DateEditor(spinnerDATE, "yyyy-MM-dd"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSAVE)
                .addGap(18, 18, 18)
                .addComponent(btnCLEAR)
                .addGap(18, 18, 18)
                .addComponent(btnUPDATE)
                .addGap(18, 18, 18)
                .addComponent(btnSEARCH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDELETE)
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSTATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerTIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(spinnerDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinnerTIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(comboSTATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel6)
                .addGap(18, 102, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSAVE)
                    .addComponent(btnCLEAR)
                    .addComponent(btnUPDATE)
                    .addComponent(btnSEARCH)
                    .addComponent(btnDELETE))
                .addGap(56, 56, 56))
        );

        jLabel1.setText("APPOINTMENT INFORMATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    int appId=-1;
    private void btnSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAVEActionPerformed
        // TODO add your handling code here:
        //code to validate patien id and doctors id exist
        try{
      Connection conn=DatabaseConnection.getConnection();
      int pid=Integer.parseInt(txtPID.getText());
      int did=Integer.parseInt(txtDID.getText());
      
      PreparedStatement checkPatient=conn.prepareStatement("SELECT patient_id FROM patients WHERE patient_id=?");
      checkPatient.setInt(1, pid);
      ResultSet rsP=checkPatient.executeQuery();
      
      PreparedStatement checkDoctor=conn.prepareStatement("SELECT doctor_id FROM doctors WHERE doctor_id=? ");
      checkDoctor.setInt(2, did);
      ResultSet rsD=checkDoctor.executeQuery();
      
      if(rsP.next()){
      JOptionPane.showMessageDialog(null,"Pateint id:"+ pid +" does not exist");
          }else if(rsD.next()){
       JOptionPane.showMessageDialog(null,"Doctor id:" + did + "does not exist");
          }else{
              
          Connection cons=DatabaseConnection.getConnection();
          
          
          String sql="INSERT INTO appointments (patient_id,doctor_id,appointment_date,appointment_time,status)VALUES(?,?,?,?,?)";
          PreparedStatement pst=cons.prepareStatement(sql);
          pst.setInt(1, pid);
          pst.setInt(2, did);
          java.util.Date appdate=(java.util.Date)spinnerDATE.getValue();
          pst.setDate(3,new java.sql.Date(appdate.getTime()) );
          java.util.Date apptime=(java.util.Date)spinnerTIME.getValue();
          pst.setTime(5,new java.sql.Time(apptime.getTime()));
          pst.setString(6,comboSTATUS.getSelectedItem().toString());
          
          pst.executeQuery();
          JOptionPane.showMessageDialog(null,"APPOINTMENT SAVED");
          
          }
              }catch(Exception e) {
              JOptionPane.showMessageDialog(null, "");
              }
    
              
    }//GEN-LAST:event_btnSAVEActionPerformed

    private void btnCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLEARActionPerformed
        // TODO add your handling code here:
        txtPID.setText("");
        txtDID.setText("");
    }//GEN-LAST:event_btnCLEARActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        // TODO add your handling code here:
        if(appId==-1){
        JOptionPane.showMessageDialog(null,"Please choose a valid");
        }
        try{
            int Patientid=Integer.parseInt(txtPID.getText());
            int Doctorid=Integer.parseInt(txtDID.getText());
            Connection conn=DatabaseConnection.getConnection();
            String sql="UPDATE appointments SET patient_id=?,doctor_id=?,appointment_date=?,appointment_time=?,status=? WHERE appointment_id=?";
            
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setInt(1,Patientid);
            pst.setInt(2, Doctorid);
            
            java.util.Date sdate=(java.util.Date)spinnerDATE.getValue();
            pst.setDate(3, new java.sql.Date(sdate.getTime()));
            
            java.util.Date tdate=(java.util.Date)spinnerTIME.getValue();
            pst.setTime(4,new java.sql.Time(tdate.getTime()));
            pst.setString(5,comboSTATUS.getSelectedItem().toString());
            pst.setInt(6,appId);
            
            pst.executeQuery();
            JOptionPane.showMessageDialog(null,"APPOINTMENT DATA SAVED");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEARCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSEARCHActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        // TODO add your handling code here:
        if(appId==-1){
        JOptionPane.showMessageDialog(null,"Please choose a valid row");
        }
        try{
        Connection conn=DatabaseConnection.getConnection();
        
        String sql="DELETE FROM appointments WHERE appointment_id=?";
        PreparedStatement pst=conn.prepareStatement(sql);
        
        pst.setInt(1,appId);
        pst.executeQuery();
        JOptionPane.showMessageDialog(null,"APPOINTMENT DELETED SUCCESFULLY");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        
        appId=Integer.parseInt(jTable1.getValueAt( row, 0).toString());
        txtPID.setText(jTable1.getValueAt(row, 1).toString());
        txtDID.setText(jTable1.getValueAt(row, 2).toString());
        //handle the jspinner
        try{
            String dateValue=jTable1.getValueAt(row, 3).toString();
            java.util.Date date=new java.text.SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
            spinnerDATE.setValue(date);
        }catch(Exception e){
        spinnerDATE.setValue(new java.util.Date());
        }
        //handle time spinner
        try{
            String timeValue=jTable1.getValueAt(row,4).toString();
            java.util.Date time=new java.text.SimpleDateFormat("HH:mm").parse(timeValue);
            spinnerTIME.setValue(time);
        }catch(Exception e){
        spinnerTIME.setValue(new java.util.Date());
        }
        //handle combo box
        String status=jTable1.getValueAt(row, 5).toString();
        comboSTATUS.setSelectedItem(status);
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLEAR;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnSAVE;
    private javax.swing.JButton btnSEARCH;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JComboBox<String> comboSTATUS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spinnerDATE;
    private javax.swing.JSpinner spinnerTIME;
    private javax.swing.JTextField txtDID;
    private javax.swing.JTextField txtPID;
    // End of variables declaration//GEN-END:variables
}
